image: node:11.4.0

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@8.0.1
  - npm install
  - ng build --prod
  - mv dist/angular-ngrx-income-expenses-app/ public/
  - ls -A
  artifacts:
    paths:
    - public
  only:
  - master
  - pages
